- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop_terraform
      - cart
      - catalogue
      - frontend
      - shipping
      - payment
      - user
  roles:
    - jenkins-jobs