- name: Single brach jenkins Jobs
  ansible.builtin.include_tasks:
    file: job.yml
  loop: "{{sp_jobs}}"

- name: Multi Branch jenkins Jobs
  ansible.builtin.include_tasks:
    file: job.yml
  loop: "{{mp_jobs}}"

