
- name: Create Multi-Branch Template
  ansible.builtin.template:
    src: mbranch.xml
    dest: /tmp/sbranch.xml

- name: Create a Multi Branch Jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.46.156:8080
    user: admin